# Generated by Django 2.1.4 on 2019-02-11 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('birthdate', models.DateField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('collegedepartment', models.CharField(max_length=30)),
                ('ExpectedYearOfGraduation', models.CharField(max_length=4)),
                ('CollegeID', models.CharField(max_length=30)),
                ('EmergencyContactRelation', models.CharField(max_length=7)),
                ('NationalID', models.CharField(max_length=30)),
                ('PassportID', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
